// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS. '
              'Run "flutterfire configure" to add support.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows. '
              'Run "flutterfire configure" to add support.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux. '
              'Run "flutterfire configure" to add support.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// 🌐 Web Configuration (optional)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_swAcsg5AZDcC3tWn_n0peRXmYnWaL3A',
    appId: '1:169582136982:web:99bce1a5ac665c4666bcb7',
    messagingSenderId: '169582136982',
    projectId: 'ostad-batch-six',
    authDomain: 'ostad-batch-six.firebaseapp.com',
    databaseURL:
    'https://ostad-batch-six-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ostad-batch-six.appspot.com', // ✅ fixed here
  );

  /// 🤖 Android Configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_swAcsg5AZDcC3tWn_n0peRXmYnWaL3A',
    appId: '1:169582136982:android:99bce1a5ac665c4666bcb7',
    messagingSenderId: '169582136982',
    projectId: 'ostad-batch-six',
    databaseURL:
    'https://ostad-batch-six-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ostad-batch-six.appspot.com', // ✅ fixed here
  );

  /// 🍎 iOS Configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLUsTiuPI3g7sQV4xr_mHhOHZdUgRKLCM',
    appId: '1:169582136982:ios:54ed9bbf4dd6335466bcb7',
    messagingSenderId: '169582136982',
    projectId: 'ostad-batch-six',
    databaseURL:
    'https://ostad-batch-six-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ostad-batch-six.appspot.com', // ✅ fixed here
    iosBundleId: 'com.ostad.firebaseLiveScoreApp',
  );
}
